- defaults:
    link:
        relink: true

- clean: ['~']

- link:
    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc
    ~/.vim: vim
    ~/.tmux: tmux

- shell:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - >
      git clean -fdx -f
      vim/bundle/
