- defaults:
    link:
        relink: true

- clean: ['~']

- link:
    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc
    ~/.vim: vim
    ~/.config/nvim: nvim
    ~/.tmux: tmux
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.config/matplotlib: config/matplotlib
    ~/.fonts: fonts
    ~/.bash_exports: bash/bash_exports
    ~/.bash_aliases: bash/bash_aliases
    ~/.bashrc: bash/bashrc
    ~/.fzf: fzf
    ~/.fzf.bash: bash/fzf.bash

- shell:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - fc-cache -vf
