- defaults:
    link:
        relink: true

- clean: ['~']

- link:
    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc
    ~/.vim: vim
    ~/.tmux: tmux
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.config/fish: config/fish
    ~/.config/omf: config/omf
    ~/.config/matplotlib: config/matplotlib
    ~/.fonts: fonts

- shell:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - >
      git clean -fdx -f
      vim/bundle/
    - fc-cache -vf
