#!/bin/bash

# Default editor
if command -v nvim > /dev/null
then
    export VISUAL=nvim
else
    export VISUAL=vim
fi
export EDITOR="$VISUAL"

export DSKRC="$PROJECTSDIR/dskrc"
export DSK_PYTHON="$DSKRC/python/inits"

export PYTHONPATH=$DSK_PYTHON
export MPLCONFIGDIR="$HOME/.config/matplotlib"

export PACKAGESDIR="$HOME/pkg"
export DOTFILES="$PROJECTSDIR/dotfiles"
export DOTLOCAL="$PROJECTSDIR/dotfiles_local"

export RUN_BASH_EXPORTS="yes"
